package Dames;


/**
* Dames/Damier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Domingo, 8 de Março de 2015 03h02min39s CET
*/

public final class Damier implements org.omg.CORBA.portable.IDLEntity
{
  public Dames.Pion pionsBlancs[] = null;
  public Dames.Pion pionsNoirs[] = null;

  public Damier ()
  {
  } // ctor

  public Damier (Dames.Pion[] _pionsBlancs, Dames.Pion[] _pionsNoirs)
  {
    pionsBlancs = _pionsBlancs;
    pionsNoirs = _pionsNoirs;
  } // ctor

} // class Damier
