package Dames;

/**
* Dames/DamierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Quarta-feira, 4 de Março de 2015 20h22min06s CET
*/

public final class DamierHolder implements org.omg.CORBA.portable.Streamable
{
  public Dames.Damier value = null;

  public DamierHolder ()
  {
  }

  public DamierHolder (Dames.Damier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Dames.DamierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Dames.DamierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Dames.DamierHelper.type ();
  }

}
