package Dames;


/**
* Dames/GestionaireDePartie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Domingo, 8 de Março de 2015 03h02min39s CET
*/

public interface GestionaireDePartie extends GestionaireDePartieOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionaireDePartie
