package Dames;

/**
* Dames/JoueurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Quarta-feira, 4 de Março de 2015 20h22min06s CET
*/


//
public final class JoueurHolder implements org.omg.CORBA.portable.Streamable
{
  public Dames.Joueur value = null;

  public JoueurHolder ()
  {
  }

  public JoueurHolder (Dames.Joueur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Dames.JoueurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Dames.JoueurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Dames.JoueurHelper.type ();
  }

}
