package Dames;


/**
* Dames/JoueurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Domingo, 8 de Março de 2015 03h02min39s CET
*/


//
public interface JoueurOperations 
{
  String nomJoueur ();
  void aToiDeJouer ();
  void partieGagnee ();
  void partiePerdue ();
} // interface JoueurOperations
