package Dames;


/**
* Dames/JoueurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Quarta-feira, 4 de Março de 2015 20h22min06s CET
*/


//
public interface JoueurOperations 
{
  String nomJoueur ();
  void aToiDeJouer ();
  void partieGagnee ();
  void partiePerdue ();
} // interface JoueurOperations
