package Dames;


/**
* Dames/PartieOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Domingo, 8 de Março de 2015 03h02min39s CET
*/


//
public interface PartieOperations 
{
  Dames.Joueur blancs ();
  Dames.Joueur noirs ();

  // nécessaires au fonctionnement du jeu
  void faireUnDeplacement (Dames.Pion pion);
  void ajouterJoueurNoirs (Dames.Joueur joueurNoirs);
} // interface PartieOperations
