package Dames;

/**
* Dames/PartieHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Domingo, 8 de Março de 2015 03h02min39s CET
*/


//
public final class PartieHolder implements org.omg.CORBA.portable.Streamable
{
  public Dames.Partie value = null;

  public PartieHolder ()
  {
  }

  public PartieHolder (Dames.Partie initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Dames.PartieHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Dames.PartieHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Dames.PartieHelper.type ();
  }

}
