package Dames;


/**
* Dames/PartiePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Quarta-feira, 4 de Março de 2015 20h22min06s CET
*/


//
public abstract class PartiePOA extends org.omg.PortableServer.Servant
 implements Dames.PartieOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_blancs", new java.lang.Integer (0));
    _methods.put ("_get_noirs", new java.lang.Integer (1));
    _methods.put ("faireUnDeplacement", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Dames/Partie/_get_blancs
       {
         Dames.Joueur $result = null;
         $result = this.blancs ();
         out = $rh.createReply();
         Dames.JoueurHelper.write (out, $result);
         break;
       }

       case 1:  // Dames/Partie/_get_noirs
       {
         Dames.Joueur $result = null;
         $result = this.noirs ();
         out = $rh.createReply();
         Dames.JoueurHelper.write (out, $result);
         break;
       }


  // nécessaires au fonctionnement du jeu
       case 2:  // Dames/Partie/faireUnDeplacement
       {
         Dames.Pion pion = Dames.PionHelper.read (in);
         this.faireUnDeplacement (pion);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Dames/Partie:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Partie _this() 
  {
    return PartieHelper.narrow(
    super._this_object());
  }

  public Partie _this(org.omg.CORBA.ORB orb) 
  {
    return PartieHelper.narrow(
    super._this_object(orb));
  }


} // class PartiePOA
