package Dames;


/**
* Dames/PartieOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Quarta-feira, 4 de Março de 2015 20h22min06s CET
*/


//
public interface PartieOperations 
{
  Dames.Joueur blancs ();
  Dames.Joueur noirs ();

  // nécessaires au fonctionnement du jeu
  void faireUnDeplacement (Dames.Pion pion);
} // interface PartieOperations
