package Dames;


/**
* Dames/pionsBlancsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dames.idl
* Domingo, 8 de Março de 2015 03h02min39s CET
*/

abstract public class pionsBlancsHelper
{
  private static String  _id = "IDL:Dames/pionsBlancs:1.0";

  public static void insert (org.omg.CORBA.Any a, Dames.Pion[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Dames.Pion[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Dames.PionHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Dames.pionsBlancsHelper.id (), "pionsBlancs", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Dames.Pion[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Dames.Pion value[] = null;
    int _len0 = istream.read_long ();
    value = new Dames.Pion[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Dames.PionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Dames.Pion[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Dames.PionHelper.write (ostream, value[_i0]);
  }

}
