package Draughts;


/**
* Draughts/PiecesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min15s CET
*/

abstract public class PiecesHelper
{
  private static String  _id = "IDL:Draughts/Pieces:1.0";

  public static void insert (org.omg.CORBA.Any a, Draughts.Piece[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Draughts.Piece[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Draughts.PieceHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Draughts.PiecesHelper.id (), "Pieces", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Draughts.Piece[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Draughts.Piece value[] = null;
    int _len0 = istream.read_long ();
    value = new Draughts.Piece[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Draughts.PieceHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Draughts.Piece[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Draughts.PieceHelper.write (ostream, value[_i0]);
  }

}
