package Draughts;


/**
* Draughts/Piece.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min14s CET
*/

public final class Piece implements org.omg.CORBA.portable.IDLEntity
{
  public Draughts.Position position = null;

  public Piece ()
  {
  } // ctor

  public Piece (Draughts.Position _position)
  {
    position = _position;
  } // ctor

} // class Piece
