package Draughts;


/**
* Draughts/PieceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min14s CET
*/

abstract public class PieceHelper
{
  private static String  _id = "IDL:Draughts/Piece:1.0";

  public static void insert (org.omg.CORBA.Any a, Draughts.Piece that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Draughts.Piece extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = Draughts.PositionHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "position",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Draughts.PieceHelper.id (), "Piece", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Draughts.Piece read (org.omg.CORBA.portable.InputStream istream)
  {
    Draughts.Piece value = new Draughts.Piece ();
    value.position = Draughts.PositionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Draughts.Piece value)
  {
    Draughts.PositionHelper.write (ostream, value.position);
  }

}
