package Draughts;


/**
* Draughts/PlayerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min15s CET
*/

abstract public class PlayerHelper
{
  private static String  _id = "IDL:Draughts/Player:1.0";

  public static void insert (org.omg.CORBA.Any a, Draughts.Player that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Draughts.Player extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Draughts.PlayerHelper.id (), "Player");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Draughts.Player read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PlayerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Draughts.Player value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Draughts.Player narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Draughts.Player)
      return (Draughts.Player)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Draughts._PlayerStub stub = new Draughts._PlayerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Draughts.Player unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Draughts.Player)
      return (Draughts.Player)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Draughts._PlayerStub stub = new Draughts._PlayerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
