package Draughts;

/**
* Draughts/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min15s CET
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public Draughts.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (Draughts.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Draughts.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Draughts.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Draughts.PlayerHelper.type ();
  }

}
