package Draughts;

/**
* Draughts/PositionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min14s CET
*/

public final class PositionHolder implements org.omg.CORBA.portable.Streamable
{
  public Draughts.Position value = null;

  public PositionHolder ()
  {
  }

  public PositionHolder (Draughts.Position initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Draughts.PositionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Draughts.PositionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Draughts.PositionHelper.type ();
  }

}
