package Draughts;


/**
* Draughts/Position.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min14s CET
*/

public final class Position implements org.omg.CORBA.portable.IDLEntity
{
  public int x = (int)0;
  public int y = (int)0;

  public Position ()
  {
  } // ctor

  public Position (int _x, int _y)
  {
    x = _x;
    y = _y;
  } // ctor

} // class Position
