package Draughts;


/**
* Draughts/RoundHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min15s CET
*/

abstract public class RoundHelper
{
  private static String  _id = "IDL:Draughts/Round:1.0";

  public static void insert (org.omg.CORBA.Any a, Draughts.Round that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Draughts.Round extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Draughts.RoundHelper.id (), "Round");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Draughts.Round read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RoundStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Draughts.Round value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Draughts.Round narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Draughts.Round)
      return (Draughts.Round)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Draughts._RoundStub stub = new Draughts._RoundStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Draughts.Round unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Draughts.Round)
      return (Draughts.Round)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Draughts._RoundStub stub = new Draughts._RoundStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
