package Draughts;

/**
* Draughts/RoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min15s CET
*/

public final class RoundHolder implements org.omg.CORBA.portable.Streamable
{
  public Draughts.Round value = null;

  public RoundHolder ()
  {
  }

  public RoundHolder (Draughts.Round initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Draughts.RoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Draughts.RoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Draughts.RoundHelper.type ();
  }

}
