package Draughts;


/**
* Draughts/RoundOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Draughts.idl
* Quarta-feira, 4 de Março de 2015 18h36min15s CET
*/

public interface RoundOperations 
{
  boolean isFinished ();
  void isFinished (boolean newIsFinished);
} // interface RoundOperations
