module Draughts
{
    struct Position
    {
        long x;
        long y;
    };

    struct Piece
    {
        Position position;
    };

    typedef sequence <Piece> Pieces;

    interface Round
    {
        attribute Player player1;
        attribute Player player2;
        attribute boolean isFinished;
    };

    interface Player
    {
        attribute Pieces pieces;
    };
};